### ISSUE TITLE
Error in translation

### ISSUE THREAD

**Issue by rickyMio** [nenes25/eicaptcha#129] opened 2019-11-21 11:22 UTC
**Prestashop Version**  
1.7.5.2

**Eicaptcha version**  
2.0.4

**Describe the bug**  
I have a multilingual e-commerce, but when I switch to english version the text of captcha does not change.

**Screenshots**  
![Screenshot 2019-11-21 at 12 22 45](https://user-images.githubusercontent.com/18484369/69333789-ababb100-0c59-11ea-8128-6c653499611f.png)

![Screenshot 2019-11-21 at 12 21 39](https://user-images.githubusercontent.com/18484369/69333707-8159f380-0c59-11ea-9690-0baca20f0b4b.png)

**Comment by alfonsolr09** [comment] 2020-03-22 12:48
Hola, lo primero que debes hacer es traducir el módulo para cada idioma.

1.  Seleccionas Traducciones
https://prnt.sc/rklrg4

2.  Seleccionas el módulo que desea traducir y el idioma
https://prnt.sc/rklrlw

3.  Ahora ya puedes traducir las palabras del módulo

**Comment by alfonsolr09** [comment] 2020-03-22 12:49
Hello, the first thing you should do is translate the module for each language.

1. You select Translations
https://prnt.sc/rklrg4

2. Select the module you want to translate and the language
https://prnt.sc/rklrlw

3. Now you can translate the words of the module

**Comment by HartLarsson** [comment] 2020-08-27 14:11
Is not a problem of translation, is a problem of language detecting that not works when you switch language from PS

**Comment by nenes25** [comment] 2021-09-06 19:02
duplicate of #162

**Closed by nenes25** 2021-09-06 19:02 UTC
Labels: 2.x
