### ISSUE TITLE
The module is not registered in hook actionContactFormSubmitCaptcha

### ISSUE THREAD

**Issue by Toshiakea** [nenes25/eicaptcha#244] opened 2023-02-11 12:31 UTC
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

< 1.7

### Eicaptcha version

2.4.x

### Do you use a specific theme ?

Yes, I use a theme named Kidshop

### Describe the bug

Sorry for my bad english, and sorry if this topic is duplicated.

I have followed several tutorial for this module, and I'm thinking that I'm doing good.

But if I try the button "Check module installation", appears the following error:

The module is not registered in hook actionContactFormSubmitCaptcha

I attached in a photo.

What can I do? Any idea? 

Thanks a lot!!!

### Screenshots

![imagen](https://user-images.githubusercontent.com/125131903/218258095-667f6525-d0db-4f90-9221-91be6318a040.png)

**Comment by nenes25** [comment] 2023-02-12 09:02
Hello,

Thanks for the report but this issue is a duplicate of #230
This is not really an issue, but just an old hook name.

Regards,

**Closed as completed by nenes25** 2023-02-12 09:02 UTC
Labels: bug
