### ISSUE TITLE
Uncaught Error: reCAPTCHA placeholder element must be an element or id

### ISSUE THREAD

**Issue by nicolasfuentes** [nenes25/eicaptcha#41] opened 2018-03-10 15:58 UTC
### Your prestashop version
1.7.1.0

### Eicaptcha Version
v2.0.2

### Do you use a specific theme
leo_martin (version 1.0.0, by Leotheme Team)

### Website
https://www.cordonne.com.ar/contactanos

### Issue description
First, thanks for the module. It helped us with a spam attack.
This is my first issue in Github.
We have a problem when some field is empty in the contact form or captcha checkbox is not clicked, and then, click on send button. This error appear:
![eicaptcha](https://user-images.githubusercontent.com/20538056/37244042-c7da818a-2461-11e8-85f0-9c1181cb730a.PNG)

If all fields have a value in the contact form and captcha checkbox is clicked, it is working fine.
Can I help me, please?
Thanks!

**Comment by nenes25** [comment] 2018-03-10 19:54
Hello,

The issue is related with your theme.
The theme js are merged in one file and load at the end of the document with an defer attribute : 
``<script type="text/javascript" src="https://www.cordonne.com.ar/themes/leo_martin/assets/cache/bottom-e810b7.js" defer ></script>``

So the module js file wich will create dynamicaly the div id="captcha-box" is not executed before the google recaptcha script is called.

The better solution in your case is to add direclty the code of the file : 
https://github.com/nenes25/eicaptcha/blob/17/views/js/eicaptcha-contact-form.js

directly in eicaptcha.php file ( https://github.com/nenes25/eicaptcha/blob/17/eicaptcha.php#L337 ) before the google recaptcha lib is called.

Regards,

**Comment by nicolasfuentes** [comment] 2018-03-20 13:22
Hello!
Sorry for delay and thanks for your feedback.
Is not worked. It is complicated with my theme.
But your feedback gave me an idea and I added directly html tags `<div id="captcha-box"></div>`
in `modules/contactform/views/templates/widget/contactform.tpl` and worked.
Regards!

**Comment by nenes25** [comment] 2018-03-20 14:14
OK  great if it works.
Thanks for the feeback, so i close the issue.

Regards,

**Closed by nenes25** 2018-03-20 14:14 UTC
Labels: 2.x, waiting user feedback
