### ISSUE TITLE
Captcha in account creation form can be bypassed

### ISSUE THREAD

**Issue by ivo2019** [nenes25/eicaptcha#124] opened 2019-09-16 21:25 UTC
** Prestashop Version **
1.7.6.1

** Eicaptcha version **
2.04

** Do you use a specific theme **
Standard free theme that comes with the installation of Presta

**Describe the bug**
When I put products in shopping cart and go to checkout, I see the 1st step to create an account and it shows the captcha module, but I can just fill in all account details and click on 'SAVE' without clicking on the captcha module and it still creates my account and moves on to the next step.
I can also change my account password without clicking on the recaptcha and just bypass it and click on SAVE.

In the contact form it works fine. However I did notice an installation error after checking the installation.:
Errors
contacform.php override does not exists
I think this is a spelling mistake in the checker ('t' of contac(t)form is missing).
In the overrides the spelling is okay and the override is created. Probably only the spelling in the check is wrong, looking for contacform instead of contactform.

**Comment by silviots** [comment] 2019-11-11 14:58
I have the same problem

**Comment by NodokaMurmevent** [comment] 2019-12-10 10:26
i also have this problem

**Comment by castellinosoftware** [comment] 2020-01-15 11:12
Hi.
I have the same problem.

** Prestashop Version **
1.7.6.2
** Eicaptcha version **
2.04

The module works correctly when you create an account from account registration form, but not when you create an account from the cart registration form (during checkout phase)

I'm not so expert in Prestashop modules development, but I think the problem is that there are two different controllers, AuthController used by account registration form and OrderController used by cart registration form.

The module Eicaptcha override AuthController (so the reCaptcha works on account registration form), but dont override OrderController.
I made a try overriding OrderController and the reCaptcha seems to work.

**Comment by ivo71** [comment] 2020-01-15 18:26
> Hi.
> I have the same problem.
> 
> ** Prestashop Version **
> 1.7.6.2
> ** Eicaptcha version **
> 2.04
> 
> The module works correctly when you create an account from account registration form, but not when you create an account from the cart registration form (during checkout phase)
> 
> I'm not so expert in Prestashop modules development, but I think the problem is that there are two different controllers, AuthController used by account registration form and OrderController used by cart registration form.
> 
> The module Eicaptcha override AuthController (so the reCaptcha works on account registration form), but dont override OrderController.
> I made a try overriding OrderController and the reCaptcha seems to work.

Can you post what you exactly changed please? Thanks so much!

**Comment by LoicHaas** [comment] 2020-01-27 12:53
> Hi.
> I have the same problem.
> 
> ** Prestashop Version **
> 1.7.6.2
> ** Eicaptcha version **
> 2.04
> 
> The module works correctly when you create an account from account registration form, but not when you create an account from the cart registration form (during checkout phase)
> 
> I'm not so expert in Prestashop modules development, but I think the problem is that there are two different controllers, AuthController used by account registration form and OrderController used by cart registration form.
> 
> The module Eicaptcha override AuthController (so the reCaptcha works on account registration form), but dont override OrderController.
> I made a try overriding OrderController and the reCaptcha seems to work.

Yes please, I have the same issue.

**Prestashop Version**  
v1.7.2.4
**Eicaptcha version**  
v2.0.4

**Comment by alfonsolr09** [comment] 2020-03-22 13:07
> Hi.
> I have the same problem.
> 
> ** Prestashop Version **
> 1.7.6.2
> ** Eicaptcha version **
> 2.04
> 
> The module works correctly when you create an account from account registration form, but not when you create an account from the cart registration form (during checkout phase)
> 
> I'm not so expert in Prestashop modules development, but I think the problem is that there are two different controllers, AuthController used by account registration form and OrderController used by cart registration form.
> 
> The module Eicaptcha override AuthController (so the reCaptcha works on account registration form), but dont override OrderController.
> I made a try overriding OrderController and the reCaptcha seems to work.


Can you explain how you did it
or send the modified file please?

**Comment by Guiguimps** [comment] 2020-04-07 16:55
@castellinosoftware and @alfonsolr09 

I added `override/controllers/front/OrderController.php`
with this content : 

```
use PrestaShop\PrestaShop\Core\Foundation\Templating\RenderableProxy;

class OrderController extends OrderControllerCore
{
    public function initContent()
    {
        if ( Tools::isSubmit('submitCreate') ) {
            Hook::exec('actionContactFormSubmitCaptcha');
            if ( ! sizeof( $this->context->controller->errors ) ) {
                parent::initContent();
            } else {
                $this->restorePersistedData($this->checkoutProcess);
                $this->checkoutProcess->handleRequest();
                $presentedCart = $this->cart_presenter->present($this->context->cart);
                
                $this->checkoutProcess
                ->setNextStepReachable()
                ->markCurrentStep()
                ->invalidateAllStepsAfterCurrent();

                $this->saveDataToPersist($this->checkoutProcess);
                
                if (!$this->checkoutProcess->hasErrors()) {
                if ($_SERVER['REQUEST_METHOD'] !== 'GET' && !$this->ajax) {
                        return $this->redirectWithNotifications(
                            $this->checkoutProcess->getCheckoutSession()->getCheckoutURL()
                        );
                    }
                }
                $this->context->smarty->assign([
                    'checkout_process' => new RenderableProxy($this->checkoutProcess),
                    'cart' => $presentedCart,
                ]);
                $this->context->smarty->assign([
                    'display_transaction_updated_info' => Tools::getIsset('updatedTransaction'),
                ]);
                
                FrontController::initContent();

                $this->setTemplate('checkout/checkout');
             }
        } else {
            parent::initContent();
        }
    }
}
```
The important thing is : 
• `$this->checkoutProcess->handleRequest();` where `handleRequest();` has no parameters
•  `FrontController::initContent();`
•  and don't forget the `use` condition in the begining of the file

I don't know if it's a good modification, but it seems to work

**Comment by alfonsolr09** [comment] 2020-04-07 22:16
> @castellinosoftware and @alfonsolr09 
> 
> I added `override/controllers/front/OrderController.php`
> with this content : 
> 
> ```
> use PrestaShop\PrestaShop\Core\Foundation\Templating\RenderableProxy;
> 
> class OrderController extends OrderControllerCore
> {
>     public function initContent()
>     {
>         if ( Tools::isSubmit('submitCreate') ) {
>             Hook::exec('actionContactFormSubmitCaptcha');
>             if ( ! sizeof( $this->context->controller->errors ) ) {
>                 parent::initContent();
>             } else {
>                 $this->restorePersistedData($this->checkoutProcess);
>                 $this->checkoutProcess->handleRequest();
>                 $presentedCart = $this->cart_presenter->present($this->context->cart);
>                 
>                 $this->checkoutProcess
>                 ->setNextStepReachable()
>                 ->markCurrentStep()
>                 ->invalidateAllStepsAfterCurrent();
> 
>                 $this->saveDataToPersist($this->checkoutProcess);
>                 
>                 if (!$this->checkoutProcess->hasErrors()) {
>                 if ($_SERVER['REQUEST_METHOD'] !== 'GET' && !$this->ajax) {
>                         return $this->redirectWithNotifications(
>                             $this->checkoutProcess->getCheckoutSession()->getCheckoutURL()
>                         );
>                     }
>                 }
>                 $this->context->smarty->assign([
>                     'checkout_process' => new RenderableProxy($this->checkoutProcess),
>                     'cart' => $presentedCart,
>                 ]);
>                 $this->context->smarty->assign([
>                     'display_transaction_updated_info' => Tools::getIsset('updatedTransaction'),
>                 ]);
>                 
>                 FrontController::initContent();
> 
>                 $this->setTemplate('checkout/checkout');
>              }
>         } else {
>             parent::initContent();
>         }
>     }
> }
> ```
> The important thing is : 
> • `$this->checkoutProcess->handleRequest();` where `handleRequest();` has no parameters
> •  `FrontController::initContent();`
> •  and don't forget the `use` condition in the begining of the file
> 
> I don't know if it's a good modification, but it seems to work

@guiguimps

I did what you said, I copied the file, but I can still skip the captcha without confirming it

**Comment by Guiguimps** [comment] 2020-04-08 14:55
Sorry, I'm not enough a good programmer to help you... I think we should wait for the next release

**Comment by ToniAlvarez** [comment] 2020-05-13 10:44
I've the same issue with Prestashop 1.7.6.5 and 2.0.4

**Comment by alfonsolr09** [comment] 2020-05-30 19:43
@nenes25 how can i do?

**Comment by eramirezprotec** [comment] 2020-10-16 13:22
[This is the solution](https://github.com/nenes25/eicaptcha/issues/124#issuecomment-610502784).

Thank you very much, @Guiguimps 

For those fighting with this problem:

1 - Create the following file: modules\eicaptcha\override\controllers\front\OrderController.php
2 - Copy the [file content](https://github.com/nenes25/eicaptcha/issues/124#issuecomment-610502784) and paste it as the new content of the file created in the previous step (remember adding "<?php" at the beginning of the file).
3 - In the BO, go to Modules > Module Manager, and find Ei Captcha (eicaptcha). Now, reset it.
4 - Configure it (Site key, Secret key, etc.)
5 - That's it. On the checkout page, you will not be able to advance unless you check the captcha.

**Comment by nenes25** [comment] 2020-10-31 21:21
Thanks all about your contributions , this is fixed now :)

**Closed by nenes25** 2020-10-31 21:21 UTC
Labels: 2.x

**Comment by alfonsolr09** [comment] 2020-10-31 21:23
Is there a new versión of the module??
