### ISSUE TITLE
incorrect response to CAPTCHA challenge. Please try again.

### ISSUE THREAD

**Issue by atolodas** [nenes25/eicaptcha#100] opened 2019-04-25 09:38 UTC
### Your prestashop version
1.6.1.23
### Eicaptcha Version
v0.4.16
### Do you use a specific theme
warehouse
### Issue description
If user make order /quick-order and create account,
CAPTCHA accepted, but when try save address ... 

Get error message
incorrect response to CAPTCHA challenge. Please try again.

**Comment by nenes25** [comment] 2019-04-25 12:19
Hi,

I can confirm there is an issue with the quick order process.
As the captcha information are not send through the ajax steps.

I'll see what i can do this fix this, but the quicker option will certainly be to remove the captcha from quick order.

Regards,

**Comment by nacxo** [comment] 2019-04-26 19:09
HI,
Ive the same issue on the same templete (warehouse) and ps 1.6.1.17...
Any solutions yet????

We need a captcha on the register form...

Thanks.

**Comment by DarekC** [comment] 2019-04-26 23:45
Hi,
Exactly the same problem :) the same versions.

Is there a fast way to remove captcha only from OPC (one page) forms?
There are two forms:
1. Create new account form
2. Fast shopping form

Regards,

**Comment by HMD-CR** [comment] 2019-04-28 08:19
Hi

Exact same issue have tried with various themes all the same..... how best to remove Captcha from OPC only as spam accounts are only created from the main create new account ..

Module works great apart from this.

Thanks

**Comment by nenes25** [comment] 2019-04-29 07:34
Hi,
Can you try with the following version ( it removes captcha only from OPC )
On my side it works well, if you can confirm i'll publish a new relase to fix it.

Regards,
[eicaptcha.zip](https://github.com/nenes25/eicaptcha/files/3126309/eicaptcha.zip)

**Comment by HMD-CR** [comment] 2019-04-29 08:08
Hi

I am still getting the recaptcha on the OPC…… I completely un-installed the module cleared all cache and then reinstalled the new version.

I have installed this on a multishop site using 3 different themes…. Same result on all 3 


Many thanks

Clive Riches







HYPERMEDIA DESIGN
Direct: +44 7870 156769    

Main Office: +44 1256 398188   Skype: cliveriches
http://www.hypermediadesign.co.uk <http://www.hypermediadesign.co.uk/>

Please be advised, the information contained herein is confidential and intended only for use by the individual stated above. 
If you are not the named recipient, you are hereby notified that any disclosure, distribution, dissemination or copying of this content is prohibited and should be deleted.
Hypermedia Design accepts no responsibility in the event that the onward transmission, opening or use of this message and/or any
included attachments adversely affects the recipient's systems or data. It is the recipient's responsibility 
to carry out any virus checks that the recipient considers appropriate.

**Comment by Evelina11** [comment] 2019-04-29 08:35
Hi
I also have recaptcha still on OPC quick-order
    Prestashop version 1.6.1.2
    Theme name default-bootstrap
    Php version 5.6.40

**Comment by mhaken** [comment] 2019-04-29 08:44
Hello,
I also have recaptcha still on OPC.
PS 1.6.1.18
PHP version 7.1

**Comment by nenes25** [comment] 2019-04-29 09:26
Sorry, the uploaded zip was not the good one ...
Here it is 
[eicaptcha.zip](https://github.com/nenes25/eicaptcha/files/3126711/eicaptcha.zip)

**Comment by Evelina11** [comment] 2019-04-29 09:47
It already works for me. See you in time.
Thank you

**Comment by mhaken** [comment] 2019-04-29 10:15
Good job @nenes25. Thank you! This version works for me.

**Comment by HMD-CR** [comment] 2019-04-29 10:32
Great Job all working now thanks

**Comment by Muchiga-Daniel** [comment] 2019-04-29 12:21
HI,
Ive the same problem on  ps 1.6.1.15...
Any solutions?

Thanks.

**Comment by nenes25** [comment] 2019-04-29 19:01
Fixed in release 0.4.17

**Closed by nenes25** 2019-04-29 19:01 UTC

**Comment by ezsassi** [comment] 2019-08-09 21:04
I am experiencing the following error while submitting contact form data! What could it be???

1 error

incorrect response to CAPTCHA challenge. Please try again.
-----------------------------------------
My prestashop!

advanded parameters
Errors 
OPC checkout is enable, be aware that the captcha won't be displayed on it
Success 
the module is compatible with your version
the module is well registered in hook header
the module is well registered in hook displayCustomerAccountForm
the module is well registered in hook contactFormAccess
the module is well registered in hook actionBeforeSubmitAccount
Overrides are enabled on your website
ContactController.php override exists
ContactController.php override is present in class_index.php
Aditionnal informations 
Prestashop version 1.6.1.7
Theme name default-bootstrap
Php version 5.6.40

Version captcha: Ei Captcha v0.4.17

**Comment by willx777** [comment] 2019-09-16 13:38
Hi nenes25,
I'm having this issue on my OPC. 
"There is 1 error(s):
incorrect response to CAPTCHA challenge. Please try again."
My site is installed with PS 1.6.1.23 and ercaptcha 0.4.17.

**Comment by JawaB** [comment] 2020-06-02 14:44
Same for me... 
PS 1.6.1.23 module 0.4.17
Contact form thrown an error "incorrect response to captcha  challenge, please try again"
