### ISSUE TITLE
reCaptcha not stopping checkout page

### ISSUE THREAD

**Issue by gonalo123** [nenes25/eicaptcha#74] opened 2018-07-05 13:32 UTC
### Your prestashop version
1.7.0
### Eicaptcha Version
2.0.4
### Do you use a specific theme
Alysum
### Issue description
The recaptcha module appears just fine in the registration form and in the first step of checkout page.
It also works fine in the registration form, but in the checkout page, if we select continue, without checking the recaptcha box, the process continues without showing any alert or error message.

**Comment by nenes25** [comment] 2018-07-09 11:07
Hi, 
Thanks for the report, i guess it is a duplicate of #48

**Closed by nenes25** 2018-07-09 11:07 UTC

**Comment by gonalo123** [comment] 2018-07-09 11:15
Thanks for the answer.
I checked the #48 issue but I 'm not understanding how the resolution of the problem is made?

**Comment by eramirezprotec** [comment] 2020-10-16 13:32
Solution [here](https://github.com/nenes25/eicaptcha/issues/124#issuecomment-710041812).
