### ISSUE TITLE
Errors - "contacform.php override does not exist" is displayed despite correct installation 

### ISSUE THREAD

**Issue by toslan** [nenes25/eicaptcha#136] opened 2019-12-20 08:09 UTC
**Prestashop Version**  
1.7.6.0

**Eicaptcha version**  
2.0.4

**Do you use a specific theme**  
My own, based on "classic-rocket"

**Describe the bug**  
Eicaptcha is installed and working OK but when "Check if module is well installed" is checked in admin backend Errors - "contacform.php override does not exists" is shown.

**Screenshots**  
![Screenshot_2019-12-20_10-56-33](https://user-images.githubusercontent.com/9819979/71239661-2549c400-2318-11ea-99f1-9139acd3a73c.png)

**Additional context**  
Probably wrong path of contacform.php is checked in the module file. If I change the line 492:
`if (!file_exists(_PS_OVERRIDE_DIR_.'controllers/modules/contactform/contactform.php')) {`
to
`if (!file_exists(_PS_OVERRIDE_DIR_.'modules/contactform/contactform.php')) {`
the error disappeares

**Comment by nenes25** [comment] 2019-12-20 08:29
Hello and thanks for the feedback,
This is effectively just a misspel in the word contaform ( duplicate of #67 )
As it not critical it's been a while i should have correct this.
Thanks for the reminder,

Regards,

**Comment by toslan** [comment] 2019-12-20 08:42
No, the spelling is correct but the path of overriden module starts with 'controllers/modules/...' which is wrong for my prestashop version. Should be changed to 'modules/...' as I pointed above. Anyway the module works fine.
Best regards,

**Closed** 2020-04-11 13:15 UTC
