### ISSUE TITLE
Impossible d'activer eicaptcha

### ISSUE THREAD

**Issue by gs2k84** [nenes25/eicaptcha#213] opened 2022-01-27 11:30 UTC
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

1.7.8.x

### Do you use a specific theme ?

Bonjour,

Lorsque vous essayez d'allumer le module, le problème suivant apparaît :

"Impossible d'activer le module eicaptcha. Impossible d'installer la superposition : la méthode postProcess de la classe OrderController a déjà été écrasée."

S'il vous plaît aider.

Les salutations.
Grégory

### Describe the bug

"Impossible d'activer le module eicaptcha. Impossible d'installer la superposition : la méthode postProcess de la classe OrderController a déjà été écrasée."

**Comment by nenes25** [comment] 2022-01-27 12:04
Hello,

The issue is pretty clear.
This module relies on overriding some native behaviors of Prestashop using a native mechanism.
And one of the function used by the module is already override by another module.

So you will need to install this override manually.

Copy the following code in the beginning of the function postProcess of file override/controllers/front/OrderController.php

`if (  
            Tools::isSubmit('submitCreate')  
            && Module::isInstalled('eicaptcha')  
            && Module::isEnabled('eicaptcha')  
            && false === Module::getInstanceByName('eicaptcha')->hookActionContactFormSubmitCaptcha([])  
            && !empty($this->errors) 
        ) {
            unset($_POST['submitCreate']);  
        }`

and remove or rename the file modules/override/controllers/front/OrderController.php

Then the module installation should works.
Regards,

**Comment by gs2k84** [comment] 2022-01-27 12:42
Thank you very much for your help.

The file has been added:

AuthController.php

then I deleted the file I created. And brought back the old one.

I don't know if that's what it was supposed to be like, but it works :)

Regards

**Comment by nenes25** [comment] 2022-01-27 15:04
Hello,
Nice to know everything works as expected now.
So i close this issue :smile: 
Regards,

**Closed as completed by nenes25** 2022-01-27 15:04 UTC
Labels: bug, waiting user feedback
