### ISSUE TITLE
JS error

### ISSUE THREAD

**Issue by soulraven** [nenes25/eicaptcha#134] opened 2019-12-03 14:22 UTC
**Prestashop Version**  
1.7.5.2

**Eicaptcha version**  
v2.0.4

**Do you use a specific theme**  
Techone

**Describe the bug**  
On login page, i get this JS error: 
```
recaptcha__ro.js:499 Uncaught Error: reCAPTCHA placeholder element must be an element or id
    at Object.rm [as render] (recaptcha__ro.js:499)
    at onloadCallback (autentificare:167)
    at $7 (recaptcha__ro.js:499)
    at recaptcha__ro.js:506
    at Jo (recaptcha__ro.js:510)
    at zW (recaptcha__ro.js:506)
    at recaptcha__ro.js:512
    at recaptcha__ro.js:532
```

**Screenshots**  

**Additional context**

**Comment by nenes25** [comment] 2019-12-03 14:47
duplicate of #135

**Closed by nenes25** 2019-12-03 14:47 UTC
