### ISSUE TITLE
ReCaptcha does not display nto default theme

### ISSUE THREAD

**Issue by Quertes** [nenes25/eicaptcha#32] opened 2018-02-26 13:03 UTC
### Your prestashop version
1.7.2.4
### Eicaptcha Version
0.4.11
### Webisite
www.tompet.cz

### Do you use a specific theme
TechOne - https://themeforest.net/item/techone-modern-prestashop-theme/20383869
### Issue description
i Installed version 0.4.11 -> fill the keys but the captcha does not display on contact form

When I switch on classic theme the captcha still does not work.

**Comment by nenes25** [comment] 2018-02-26 13:12
Hello,

You seems to have js error in your page as you can see above : 
![js-error](https://user-images.githubusercontent.com/7163132/36672266-fcc11420-1afe-11e8-9f1e-46e4cf2f19f1.JPG)

Please try to correct them before in order to see in they are the cause of the error.

Regards,
Hervé

**Comment by Quertes** [comment] 2018-02-26 14:56
I repair the errors. 

When I unnistall the module EI Captcha then i dont have any error.

Then I install Ei Captcha ang i get it 2 errors.

**Comment by Quertes** [comment] 2018-03-02 08:35
i install 0.4.11 then 2.0.0be verison and the captcha display on contact form. But no need check it, can send mesasage anyway - any solutions?

**Comment by nenes25** [comment] 2018-03-02 11:06
Hello,
If you have ps 1.7 , download the last release : https://github.com/nenes25/eicaptcha/releases/tag/2.0.3 
Then enable the debug mode.
And check if log are populated.

Regards,

**Comment by Quertes** [comment] 2018-03-02 11:58
Thank you, i installed the new version. The captcha is on my website. But still no need to check it and its possible send msg withou checking the captcha.

In directory logs are only index.php

Petr.

**Comment by Apicedda** [comment] 2018-03-02 12:37
Same issue, captcha box appears but you don't need to check it to be able to send a message. No errors in console and log file is not created at all.

**Comment by nenes25** [comment] 2018-03-05 12:59
The issue seems to be the same as #24

**Comment by nenes25** [comment] 2018-03-05 12:59
Duplicate of #24

**Comment by nenes25** [comment] 2018-03-11 15:34
Closed as duplicate of #24

**Closed by nenes25** 2018-03-11 15:34 UTC
Labels: 2.x
