### ISSUE TITLE
Validation in Captcha

### ISSUE THREAD

**Issue by jorgerey89** [nenes25/eicaptcha#24] opened 2018-02-21 12:17 UTC
### Your prestashop version
Prestashop 1.7.2.4
### Eicaptcha Version
"branch 17" (2.0.2) 
### Do you use a specific theme
nerva
### Issue description
It works correctly and is displayed in the contact form. But it does not validate the recaptcha. Example, fill all fields and do not check the recaptcha and when I give to send the form is sent. You should not let me send the form with the recaptcha not checked.

Can you make the form validate whether it is checked or not the recaptcha?

**Comment by nenes25** [comment] 2018-02-21 12:26
Hello,

This behaviour is the default one.
As you can see on my test website : http://web.h-hennes.fr/prestashop/prestashop_1-7-2-4/index.php?controller=contact

It should be related with your theme.
I've already make an issue to add the feature in back office #22 

Regards,

**Comment by AeffeLab** [comment] 2018-02-26 16:01
Hello,

Me too I have always the problem of the validation captcha. I test your link site but there is the same error: see attached file.
![error_captcha](https://user-images.githubusercontent.com/36855480/36680656-aeaa8524-1b16-11e8-9daf-5ffa67587fc8.jpg)

Please let me know.

Thanks
Angela

**Comment by AeffeLab** [comment] 2018-02-26 17:07
Hello,

I solved it, the problem was the parameter in php.ini allow_url_fopen=0 I changed it in allow_url_fopen=on

Thanks
Angela

**Comment by nenes25** [comment] 2018-02-27 07:58
OK great !
Thanks for the feedback @AeffeLab 
@jorgerey89 can you check if it corrects your problem also ?
My dev server is currently down i cannot test directly.

Regards,

**Comment by azmtb** [comment] 2018-02-27 11:24
Hi all, also receiving the same error. allow_url_fopen doesn't seem to help.

**Comment by jorgerey89** [comment] 2018-02-27 11:31
Hello @nenes25 and @AeffeLab 
I made a function in jquery to solve the validation of the captcha. It's just a small script, embedded in some .js of any prestashop theme.
It is the only solution I have found.

`$('.contact-form form').on('submit', function(e) {

  if(grecaptcha.getResponse() == "") {
    e.preventDefault();
    alert("You can not leave the Captcha empty.");
    return false;
  } else {
		
    return true; 
  }
});`

**Comment by nenes25** [comment] 2018-02-27 11:50
@jorgerey89 nice.
You can override the file views/js/eicaptcha-contact-form.js in your theme and add the content after.
So it will be only included if needed, i'll check how can i implements this in the default module
Is the issue corrected on your side ?

@azmtb  Can you give me your prestashop version and theme ?

**Comment by azmtb** [comment] 2018-02-27 11:52
@nenes25 gladly, it's prestashop 1.7.2.4
PHP version: 5.6.33

---------------

@jorgerey89 this is a bad fix by design because it's purely clientside. Anyone could go in clientside and remove this fix, then submit the form without completing the captcha. It needs to be server-side.

**Comment by azmtb** [comment] 2018-02-27 11:53
@nenes25 I'm just doing some digging myself and reading through the code, it appears `hookActionContactFormSubmitBefore` isn't even being fired.

**Comment by jorgerey89** [comment] 2018-02-27 11:57
@azmtb What solution do we give for the one that runs on the server?

**Comment by azmtb** [comment] 2018-02-27 11:58
OK - @nenes25 - problem found. It isn't hooking into contactform correctly. If I add `Hook::exec(xxxxxx);` stuff to modules/contactform/contactform.php under the `sendMessage` function it works.

**Comment by nenes25** [comment] 2018-02-27 12:02
@azmtb : This is why i've made an override of the module , see : https://github.com/nenes25/eicaptcha/blob/17/override/modules/contactform/contactform.php#L9
The function is called before the parent one.

I guess some issues may be related with the fact that the override is not found.
Could you try to remove the file app/prod/class_index.php in order to check ?

**Comment by azmtb** [comment] 2018-02-27 12:04
@nenes25 something related may be that upon installing the module it said the module "contactform" doesn't exist- but it does - does it have a new name in 1.7?

Sure, I can remove it and check.

**Comment by azmtb** [comment] 2018-02-27 12:06
@nenes25 - removing that file doesn't have any effect, still getting "Your message has been successfully sent to our team." when I don't touch the reCaptcha.

**Comment by nenes25** [comment] 2018-02-27 12:16
The problem should be linked with this message.
As the captcha module override contacform, if it is not installed correctly the override will not work.

You don't find it in the module page ?
![contactform](https://user-images.githubusercontent.com/7163132/36728260-6bd4d4c0-1bc0-11e8-9c6a-14fd668dfdcb.JPG)

**Comment by azmtb** [comment] 2018-02-27 12:27
OK - weird. Prestashop ships the `contactform` module by default but it turns out it isn't actually "installed" - it works but it wasn't in the "installed" state. Anyway, I hit "Install" and it installed it just fine with no issues. 

Now it works, _sort of_. It correctly tells me I have to fill in the reCaptcha, and if I do it tells me my form was sent but no emails are sent from the form.

**Comment by nenes25** [comment] 2018-02-27 12:48
OK that's already best.
But i can't explain how do you have installed the captcha module before the contactform one.
As i've add it as a dependency  ( see : https://github.com/nenes25/eicaptcha/blob/17/eicaptcha.php#L53 )

**Comment by jorgerey89** [comment] 2018-03-01 08:58
@nenes25 some final solution to validate the captcha?

**Comment by nenes25** [comment] 2018-03-01 09:17
I've checked again, and it still works well on my dev version.

In order to solve the problem, i plan to make a new release with a debug mode.
Thus the whole process could be tracked and it'll help me to see from where the problem comes from.

The next release should be done today or this week-end.

Regards,

**Comment by jorgerey89** [comment] 2018-03-01 09:19
@nenes25 okay thanks!

**Comment by nenes25** [comment] 2018-03-01 12:39
Hello,

Can you try the version of the attachement ?
[eicaptcha.zip](https://github.com/nenes25/eicaptcha/files/1771155/eicaptcha.zip)

And active debug in admin : 
![eicaptcha-debug](https://user-images.githubusercontent.com/7163132/36845185-fe59669e-1d55-11e8-8559-dea6d7c02a72.JPG)

Then make your tests and check the logs in the module directory in file /logs/debug.log.
Let me know if you found something weird or an error.

Regards,

**Comment by jorgerey89** [comment] 2018-03-01 12:53
@nenes25 Hi, I have updated the new version 2.0.3 and I have activated the debug mode of the module in the Advanded parameters tab.

I have made the test of sending the activated form the captcha and deactivating it, but I have not written anything in the file "/eicaptcha/logs/debug.log" I have given 777 permissions to the file and the directory but it does not write anything.

**Comment by nenes25** [comment] 2018-03-01 13:01
Ok so it means that the module is not correctly installed, and the function is not called.
Can you try to remove completely the module and to reinstall it ?

**Comment by jorgerey89** [comment] 2018-03-05 09:30
@nenes25 hello, I have unpacked the module from the prestashop panel and deleted the files from ftp. I have reinstalled the module version 2.0.3 and the debug mode of the module still does not work. (I have it activated)

**Comment by Quertes** [comment] 2018-03-06 10:59
[debug.log](https://github.com/nenes25/eicaptcha/files/1784667/debug.log)

I send the debug log.txt. After reinstall the module the debug mode works but the validiation of captcha doesnt work at all.

**Comment by nenes25** [comment] 2018-03-06 12:52
Hello @Quertes ,
This content cannot be the debug.log of the module as i only write some information linked to the module
This file semmes to be the class_index.php which defines all classes overrides

**Comment by jorgerey89** [comment] 2018-03-06 12:58
@nenes25 Hello, I have solved the problem, I have installed the "Contac form" module of prestashop 1.7 and the captcha validation works for me already.

**Comment by nenes25** [comment] 2018-03-06 13:26
OK great,
But i can't explain how you have installed it without having installing the module contactform before.
As it declared as a depedency and prestashop should not allow to install the module if it's not the case.

**Comment by Quertes** [comment] 2018-03-06 14:54
Hi,
I try uninstall contactform. And now i dont see this module (see attachment).
![contactform](https://user-images.githubusercontent.com/36849631/37038986-997df74e-2156-11e8-9bf2-83cbf7b5ace9.jpg)

**Comment by nenes25** [comment] 2018-03-10 20:55
Hello,
Could you please update to the last release ?
https://github.com/nenes25/eicaptcha/releases/tag/2.0.4
It add a tools which check if the module is well installed ( for backend code )

Regards,

**Comment by Quertes** [comment] 2018-03-10 21:03
I cant installed contactform. I Dont see IT in modules. Now i cant tested your new version.

**Comment by nenes25** [comment] 2018-03-10 21:35
Hello @Quertes ,

That's not a problem you can download it direclty from github https://github.com/PrestaShop/contactform 

Regards,

**Comment by Quertes** [comment] 2018-03-12 10:16
I get this error:
 Errors 

- the module is not registered in hook actionContactFormSubmitCaptcha
- the module is not registered in hook actionContactFormSubmitBefore
- contacform.php override does not exists

and the captche is not display on my website.

**Comment by nenes25** [comment] 2018-03-12 10:33
Ok so it explain why it's not working properly.
Try to install and remove completely the module, then to reinstall it.

**Comment by Quertes** [comment] 2018-03-12 11:24
After reinstall, its ok. Thank you very much. Petr.

**Comment by nenes25** [comment] 2018-03-12 12:25
OK great thank for the feedback.
I guess that this issue is now fixed so i close it.

**Closed by nenes25** 2018-03-12 12:25 UTC
Labels: 2.x, waiting user feedback
