### ISSUE TITLE
Formulaire invalide

### ISSUE THREAD

**Issue by dscyfer** [nenes25/eicaptcha#173] opened 2021-01-25 09:10 UTC
**Prestashop Version**  
1.6.1.4

**Eicaptcha version**  
0.4.17

**Do you use a specific theme**  
theme1164

**Describe the bug**  
No matter what we input on the fields, this error is thrown after captcha is validated and form is submitted. The error is also not in English language like it supposed to.

**Screenshots**  
![image](https://user-images.githubusercontent.com/2071539/105684478-f8f77280-5f2f-11eb-9a2f-6dd540508ef5.png)

**Comment by nenes25** [comment] 2021-01-25 12:42
Hi,

Could you please provide an url ?
Do you use a custom module to deals with forms ?
Because the error seems to be related with the form validation rather than with the captcha one.

Regards,

**Comment by dscyfer** [comment] 2021-01-26 05:01
**URL** 
[https://expresspromo.com.au/contact-us](https://expresspromo.com.au/contact-us)

Hello,
There were none that I am aware of. If there is a custom module that deals with the forms, I am unable to trace it.

**Comment by nenes25** [comment] 2021-01-26 16:15
Hello,

Thanks for the url i manage to reproduce the issue on your website.
Unfortunately this error message is not from my module as you can see if i search for "formulaire"
![image](https://user-images.githubusercontent.com/7163132/105871476-a3879800-5ff9-11eb-9c94-2eee5754279f.png)

There is nothing related with the error you provide.
Could you search for the related text in your website ?

`grep -nri "formulaire" /your/website/directory`

Regards,

**Comment by dscyfer** [comment] 2021-01-27 04:27
Hello,

this is the result of the grep search
![image](https://user-images.githubusercontent.com/2071539/105942896-19900b80-609b-11eb-97b7-913404839987.png)

Edit: has found the offending code and removed the overriding module. thanks! 😄

**Comment by nenes25** [comment] 2021-01-27 07:56
Hello,

Great as we can see in your screenshot the issue is related with an override on the contactController which is not from my module :smile: 
As you have corrected on your side i close the issue.

Regards,

**Closed as completed by nenes25** 2021-01-27 07:56 UTC
Labels: waiting user feedback
