### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Link-1110** [nenes25/eicaptcha#182] opened 2021-04-06 18:18 UTC
**Prestashop Version**  
1.7.7.3

**Eicaptcha version**  
2.1.0

**Do you use a specific theme**  
Anghar theme

**Describe the bug**  

I have errors and I don't know how to deal with them

**Screenshots**  

and I have this as an error
![Capture2](https://user-images.githubusercontent.com/77692194/113764748-ac909600-971b-11eb-95ee-cc530dd08f82.JPG)

**Comment by Rantanplan1110** [comment] 2021-04-06 18:30
Je précise qu'avant la mise a jour de PrestaShop le module fonctionné très bien.

**Comment by Rantanplan1110** [comment] 2021-04-06 18:35
The module works perfectly in the contact form
![Capture1](https://user-images.githubusercontent.com/77692194/113761261-8c5ed800-9717-11eb-9ef8-e273b10e66c0.JPG)

**Comment by Rantanplan1110** [comment] 2021-04-06 19:05
and I have this as an error
![Capture2](https://user-images.githubusercontent.com/77692194/113764748-ac909600-971b-11eb-95ee-cc530dd08f82.JPG)

**Comment by nenes25** [comment] 2021-04-07 20:24
Hello,

Which errors  and on which form ? ( contact / registration ) 
Can you try to manually hook the module to hook "displayHeader" in back office ?

Regards,

**Comment by Link-1110** [comment] 2021-04-08 18:07
Hello thank you for your answer, I do not understand where you want me to hang the module in the Back office.



I followed your tutorial on https://www.h-hennes.fr/blog/2021/03/15/prestashop-ajout-un-captcha-sur-linscription-a-la-newsletter/
This deleted an error, but your module remains invisible when registering for the newsletter.

![Capture](https://user-images.githubusercontent.com/77692194/114076968-90b9fb00-98a7-11eb-9a7e-57fde7ef231d.JPG)

here is the error I still have to correct and I don't know how

![Capture2](https://user-images.githubusercontent.com/77692194/114077007-9adbf980-98a7-11eb-9f12-a0646fdd83c1.JPG)

cordially

De : Hervé H.
Envoyé le :mercredi 7 avril 2021 22:24
À : nenes25/eicaptcha
Cc : Rantanplan1110; Author
Objet :Re: [nenes25/eicaptcha] Errors (#182)

Hello,
Which errors and on which form ? ( contact / registration )
Can you try to manually hook the module to hook "displayHeader" in back office ?
Regards,

**Comment by nenes25** [comment] 2021-04-08 19:45
Hi,
Sorry i didn't mean to hook the module in a back office hook.
But to add the module to the hook displayHeader through the back office :)
In fact i manage to reproduce the issue on a new instance, and the debug message seems to be a false positive in my case.
Could you provide an url ?

Regards,

**Comment by Link-1110** [comment] 2021-04-09 13:37
I found where the problem came from.  another cookie management module that
erased your module.  thank-you for your prompt response.

cordially

**Comment by nenes25** [comment] 2021-04-09 14:15
Great thanks for the feedback, so i close the issue.

**Closed as completed by nenes25** 2021-04-09 14:15 UTC
Labels: waiting user feedback
