### ISSUE TITLE
Error when click submit on contact form.

### ISSUE THREAD

**Issue by nbexiga** [nenes25/eicaptcha#59] opened 2018-04-13 16:43 UTC
###Prestashop version
![38731774-9df56d90-3f13-11e8-99b2-9970dd3b0d49](https://user-images.githubusercontent.com/34128424/38747252-35c47714-3f42-11e8-94e0-5ffa329c60e7.JPG)
 1.7.3

### HI
i am having an error after submit the contact form...
it validates the captcha but does not send message.
i am using prestashop 1.7.3 and the module updated to the last version.
can you kindly help?
thanks

**Comment by nenes25** [comment] 2018-04-14 06:50
Hello,
I didn't manage to replicate the issue.
This message can be launch at several places in module contactform ( see : https://github.com/PrestaShop/contactform/blob/master/contactform.php )

Can you tell me which one is called ?

Regards,

**Comment by nbexiga** [comment] 2018-04-14 07:53
HI
where can i see that? sorry but did not understand.
i have the module activated for the contact form. 
and when click on verify captcha it says verified, but after that give that error in red.
also in the configuration of the module in the test i have other error, i dont know if its related with this.
kindly see atached
![config](https://user-images.githubusercontent.com/34128424/38765855-48ec8adc-3fc1-11e8-9072-063327b5f7d7.JPG)

**Comment by nenes25** [comment] 2018-04-14 08:12
With the errors i seen on the screenshot, 
try to remove and reinstall the module , it seems that it'is not well installed.

**Comment by nbexiga** [comment] 2018-04-14 08:28
I already did it two times.
And also I already installed I  another page that I have and it's the same error.. :(
I cleaned up cache too :(

**Comment by nbexiga** [comment] 2018-04-14 08:29
The log from the module it appear ok. 
Say that the Google verification  was ok... but still the same and the message is not sended..

**Comment by Picoteur** [comment] 2018-04-14 08:47
Try to downgrade contactform from v4.0 to v3.0
It works for me

**Comment by nbexiga** [comment] 2018-04-14 09:13
Where to get that version?
I think I already installed that one .
It's one that don't have the advanced parameters tab right?

**Comment by nbexiga** [comment] 2018-04-14 11:28
How do i downgrade the contact form?

**Comment by nenes25** [comment] 2018-04-14 11:30
@Picoteur : it's not an option, the **0.3 version is not for ps 1.7**

**Comment by nenes25** [comment] 2018-04-14 11:32
duplicate of #58

**Comment by nbexiga** [comment] 2018-04-14 11:55
even if i delete the module eicaptcha now the issue persist... :(:( cannot send. the same error but now with the module uninstalled

**Comment by nenes25** [comment] 2018-04-14 11:57
So the issue is related with the contactform module.
Please delete file override/modules/contactform/contactform.php if present then 
app/cache/prod/class_index.php

**Comment by nbexiga** [comment] 2018-04-14 12:30
Do I have to delete also the class_index.php file?

**Comment by nbexiga** [comment] 2018-04-14 12:32
But I do that with the module installed? Because now even with the module uninstalled it gives the error

**Comment by nenes25** [comment] 2018-04-14 14:38
in both case after the module install and desinstall as it adds a new override.

**Comment by nbexiga** [comment] 2018-04-14 14:46
Hi
Unfortunately it happens the same.. :(:(:
I don't know more what to do...
I really need the form working... grrrrr.
Kindly help :)

**Comment by Picoteur** [comment] 2018-04-14 14:59
Sorry about that, nenes, but i got exactly the same problem than nbexiga...
even without eicaptcha, contact form get this error.
On my installation, everything works fine before updating contactform module from the prestashop BO notifications (from 3.0 to 4.0).
As soon as i came back to contactform module version 3.0, no more error sending emails...
I will try again tomorrow for confirmation.
Bye
P.

**Comment by nbexiga** [comment] 2018-04-14 15:27
Hi Picoteur
but even i intall the 3.0 again the issue persist :(:(

**Comment by nbexiga** [comment] 2018-04-14 16:00
any solution for this? probably an issue with the contact form... not with the module eicaptcha ;(;(

**Comment by nenes25** [comment] 2018-04-16 07:14
@Picoteur sorry i missunderstand what you've said ... you talk about the contactform version, not eicaptcha.
I'll check with the last contacform version i guess the error is linked to that.

**Comment by nenes25** [comment] 2018-04-16 07:42
OK I've found the error which is well related to the contactform module.
When you update it, the template is still override in the classic theme with the old file which is not compatible anymore.
The solution is to replace the file \themes\classic\modules\contactform\views\templates\widget\contactform.tpl with the new one : ( be carrefull to take the one compatible with your ps version : https://github.com/PrestaShop/PrestaShop/blob/1.7.3.x/themes/classic/modules/contactform/views/templates/widget/contactform.tpl )

**Comment by nbexiga** [comment] 2018-04-16 10:56
Hi @nenes25  where can i download the new tpl for prestashop 1.7.3.0  to test 
many thanks

**Comment by nbexiga** [comment] 2018-04-16 11:09
HI ;)

it's working now the contact form! ;) 

can i install now the module eicaptcha?
thanks

**Comment by nenes25** [comment] 2018-04-16 11:27
Yes everything should works now, as the issue was related to this template.

**Comment by nbexiga** [comment] 2018-04-16 11:32
Ok, working now! ;) many many thanks @nenes25  for your help on this.
one more issue fixed in my store ! ;)

**Comment by nenes25** [comment] 2018-04-16 13:12
Ok great, so i close the issue ;)

**Closed by nenes25** 2018-04-16 13:12 UTC
Labels: 2.x, waiting user feedback

**Comment by Joe1965** [comment] 2019-04-26 23:00
Hello, Nenes25,
I have installed you module version to solve spamming in account creation.
I use PS 1.6.1.18 with your module v0.4.15 after test the account spamming will continue, I have red that the new version solve it the 4.16 I have installed it on my Prestashop the issue seems solved for spamming, but now I have the error on contact-us window.
"Une erreur s'est produite pendant l'envoi du message"
I have de-installed your module but the problem is still there, any idea how I can solve it?
Thanks in advance for your help.

**Comment by wikao2** [comment] 2019-05-09 13:41
Bonjour Nenes25,
Merci pour votre module de captcha. J'ai Prestashop 1.7.5.1 et j'ai le message "contacform.php override does not exists".
Le 16 avril 2018, vous écriviez :
"La solution est de remplacer le fichier \themes\classic\modules\contactform\views\templates\widget\contactform.tpl par le nouveau: (soyez sûr de prendre celui qui est compatible avec votre version ps: https://github.com/PrestaShop/PrestaShop/blob/1.7.3.x/themes/classic/modules/contactform/views/templates/widget/contactform.tpl)"
J'ai donc remplacé le fichier contactform.tpl par celui téléchargé ici : https://github.com/PrestaShop/PrestaShop/blob/1.7.5.x/themes/classic/modules/contactform/views/templates/widget/contactform.tpl (puisque j'ai Prestashop 1.7.5.1).
Cependant, je continue d'avoir le même message d'erreur. Savez-vous pourquoi ?
---------
Hello Nenes25,
Thank you for your captcha module. I have Prestashop 1.7.5.1 and I have the message "contacform.php override does not exists".
On April 16, 2018, you wrote:
"The solution is to replace the /themes/classic/modules/contactform/views/templates/widget/contactform.tpl file with the new one: (be sure to take one that is compatible with your ps version: https://github. com/PrestaShop/PrestaShop/blob/1.7.3.x/themes/classic/modules/contactform/views/templates/widget/contactform.tpl) "
So I replaced the contactform.tpl file with the one downloaded here: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.x/themes/classic/modules/contactform/views/templates/widget/contactform.tpl (since I have Prestashop 1.7.5.1).
However, I still have the same error message. Do you know why ?

**Comment by onfre** [comment] 2020-03-28 21:48
Bonjour Nenes25, je rencontre le même problème sur la version 1.7.6.2, merci pour ce module indispensable !
Comment faire fonctionner le module sans avoir l'erreur malgré la modification/remplacement du fichier tpl ?
Merci beaucoup pour votre aide.
