### ISSUE TITLE
Error message when submitting: Please validate the captcha field before submitting your request

### ISSUE THREAD

**Issue by angelcasellas24** [nenes25/eicaptcha#117] opened 2019-08-05 18:15 UTC
Hi,
I have a site (https://www.flamentex.es/es/inicio-sesion?back=my-account#account-creation) with your module installed and when I try to sign up a user, the form tells me "Please validate the captcha field before submitting your request" but I have already validated and captcha returned ok.

What could be wrong?

Thanks for your comments.

Angel

**Comment by nenes25** [comment] 2019-08-08 12:44
Hi,

Could you please fill the required fields when submitting an issue ?
Prestashop version / Module version / Theme / etc..

Regards,

**Comment by angelcasellas24** [comment] 2019-08-08 12:52
Hi!
Sorry. Here are the details:
- Prestashop version: 1.6.1.19
- Module version: 0.4.17
- Theme: TSP Maian Theme

By clicking the link I pasted, when you fill the email and click "Crear una cuenta", it redirects you to the form where the captcha is.

What could it happen?

Thanks!
Angel

**Comment by nenes25** [comment] 2019-08-13 07:33
Hello,
Weird, i'm not able to reproduce your issue with a fresh installation.
I'll investigate more.

Regards,

**Comment by angelcasellas24** [comment] 2019-08-26 07:36
Hi @nenes25,
Could you find the reason of the problem?
Do you need something else?

Regards,
Angel

**Comment by dreamtheme** [comment] 2019-09-13 07:48
Hi @nenes25 
No its not the theme, and as i know what you gonna say, i switched to the default theme. Same issue.
![Screenshot_2019-09-13 Contact us](https://user-images.githubusercontent.com/17176009/64845919-039fb900-d614-11e9-8fc0-726dd3e46644.png)

**Comment by nenes25** [comment] 2019-09-13 08:02
Hi,
Thanks for the feebback and the try with the default theme
That's weird, can you give me an url ?

**Comment by dreamtheme** [comment] 2019-09-13 08:20
The original URL is a production live URL, so i setup brand new untouched PS 1.7.6.1 installation and installed the module, still happens. 
Here is URL: https://dreamtheme.eu/presta17/index.php?controller=contact

**Comment by dreamtheme** [comment] 2019-09-16 10:53
Do you still need the URL to be up?

**Comment by dreamtheme** [comment] 2019-09-25 21:04
Any news on this issue?

**Comment by nenes25** [comment] 2019-09-27 07:07
Hi,
Sorry for the late reply.
I'm aware of the lack of support on this module since several weeks ( month ... ), but i do it during my free time which is very rare, i'll try to plan a  week to check all the remaining issues in the following weeks. 

Thanks for your understanding,
Regards

**Comment by dreamtheme** [comment] 2019-09-27 21:01
Hi,
Yeah, i understand you :) don't worry, appreciate your work and thanks.

Regards

**Comment by guanacazo** [comment] 2020-01-27 22:58
For those that still need help on this: 
Happens when the ipv6 is the default or only solver (dns) answer. 
$wget https://www.google.com/recaptcha/siteverify
--2020-01-27 15:30:28--  https://www.google.com/recaptcha/api/siteverify
Resolving www.google.com (www.google.com)... 2607:f8b0:4000:817::2004, 172.217.14.164
Connecting to www.google.com (www.google.com)|2607:f8b0:4000:817::2004|:443... 
****NEVER GET THE ANSWER******
after doing:
 $sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1 net.ipv6.conf.all.disable_ipv6 = 1
$ sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1 net.ipv6.conf.default.disable_ipv6 = 1
You get: 
$ wget https://www.google.com/recaptcha/api/siteverify
--2020-01-27 15:34:39--  https://www.google.com/recaptcha/api/siteverify
Resolving www.google.com (www.google.com)... 172.217.14.164, 2607:f8b0:4000:817::2004
Connecting to www.google.com (www.google.com)|172.217.14.164|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: ‘siteverify’
siteverify                                   [ <=>                                                                               ]     103  --.-KB/s    in 0s      
2020-01-27 15:34:39 (7.18 MB/s) - ‘siteverify’ saved [103]

That was my problem

Thanks your reading! and thanks Mr Owner. 
Regards

**Comment by onfre** [comment] 2020-03-29 08:28
Hello, so what do we need to do, i don't understand ! Thank you.

I meet the same issue with my 1.7.6.2 prestashop version :

"Please validate the captcha field before submitting your request" but I have already validated and captcha returned ok.

I have tried to replace the contactform.tpl file with the good one from this page https://github.com/PrestaShop/PrestaShop/blob/1.7.6.x/themes/classic/modules/contactform/views/templates/widget/contactform.tpl
My module is the eicaptcha 2.0.4

Thank you.

**Comment by wlinker** [comment] 2020-09-09 23:39
Dejaré mi aportación en español, porque es mi lengua de origen.

en mi caso, el problema era la seguridad de PHP, tenia deshabilitado: 
allow_url_fopen

y mi proveedor no me daba opción para activarla, aún cuando tenía acceso al php.ini

así que opté por modificar el siguiente archivo:
**myinstall.../modules/eicaptcha/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/Curl.php**

Solo fue cambiar el método Request, de esto:
**_línea 74:  $this->requestMethod = new RequestMethod\Post();_** 

a esto:
**_línea 74: $this->requestMethod = new RequestMethod\CurlPost();_** 

y mi problema fue solucionado, la versión de prestashop trabajada es:
**1.7.5.2**

Ojalá a alguien más le sirva, por cierto, detecté el problema activando el debugueo en prestashop.

**Closed** 2021-05-05 20:14 UTC
